<?php

function http_post_data($url, $data_string) {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $data_string);
    curl_setopt($ch, CURLOPT_HTTPHEADER, array(
        'Content-Type: application/json; charset=utf-8',
        'Content-Length: ' . strlen($data_string))
    );
    ob_start();
    curl_exec($ch);
    $return_content = ob_get_contents();
    ob_end_clean();

    $return_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    return array($return_code, $return_content);
}

function uuid($prefix = '')  
{  
    $chars = md5(uniqid(mt_rand(), true));  
    $uuid  = substr($chars,0,8) . '-';  
    $uuid .= substr($chars,8,4) . '-';  
    $uuid .= substr($chars,12,4) . '-';  
    $uuid .= substr($chars,16,4) . '-';  
    $uuid .= substr($chars,20,12);  
    return $prefix . $uuid;  
}

$currenttime = date("y-m-d H:i:s", time());
$currentday = date("y-m-d", time());

$deviceid1 = uuid();
$deviceid2 = uuid();
$deviceid3 = uuid();
$deviceid4 = uuid();
$userid1 = uuid('userid-');
$userid2 = uuid('userid-');
$userid3 = uuid('userid-');
$userid4 = uuid('userid-');
$roleid1 = uuid('roleid-');
$roleid2 = uuid('roleid-');
$roleid3 = uuid('roleid-');
$roleid4 = uuid('roleid-');
$rolename1 = uuid('rolename-');
$rolename2 = uuid('rolename-');
$rolename3 = uuid('rolename-');
$rolename4 = uuid('rolename-');
$orderid1 = uuid('orderid-');
$orderid2 = uuid('orderid-');
$orderid3 = uuid('orderid-');
$orderid4 = uuid('orderid-');

$login_roleLevel1 = rand(1,10);
$login_roleLevel2 = rand(1,10);
$login_roleLevel3 = rand(1,10);
$login_roleLevel4 = rand(1,10);
$login_roleVip1 = rand(1,10);
$login_roleVip2 = rand(1,10);
$login_roleVip3 = rand(1,10);
$login_roleVip4 = rand(1,10);
$login_goldCoin1 = rand(100,10000);
$login_goldCoin2 = rand(100,10000);
$login_goldCoin3 = rand(100,10000);
$login_goldCoin4 = rand(100,10000);
$login_sliverCoin1 = rand(100,10000);
$login_sliverCoin2 = rand(100,10000);
$login_sliverCoin3 = rand(100,10000);
$login_sliverCoin4 = rand(100,10000);

$login_roleLevel11 = $login_roleLevel1+1;
$login_roleLevel21 = $login_roleLevel2+1;
$login_roleLevel31 = $login_roleLevel3+1;
$login_roleLevel41 = $login_roleLevel4+1;
$login_roleVip11 = $login_roleVip1+1;
$login_roleVip21 = $login_roleVip2+1;
$login_roleVip31 = $login_roleVip3+1;
$login_roleVip41 = $login_roleVip4+1;
$login_goldCoin11 = $login_goldCoin1+300;
$login_goldCoin21 = $login_goldCoin2+300;
$login_goldCoin31 = $login_goldCoin3+300;
$login_goldCoin41 = $login_goldCoin4+300;
$login_sliverCoin11 = $login_sliverCoin1+300;
$login_sliverCoin21 = $login_sliverCoin2+300;
$login_sliverCoin31 = $login_sliverCoin3+300;
$login_sliverCoin41 = $login_sliverCoin4+300;

$pay_roleLevel1 = $login_roleLevel1+1;
$pay_roleLevel2 = $login_roleLevel2+1;
$pay_roleLevel3 = $login_roleLevel3+1;
$pay_roleLevel4 = $login_roleLevel4+1;
$pay_roleVip1 = $login_roleVip1+1;
$pay_roleVip2 = $login_roleVip2+1;
$pay_roleVip3 = $login_roleVip3+1;
$pay_roleVip4 = $login_roleVip4+1;
$pay_goldCoin1 = $login_goldCoin1+300;
$pay_goldCoin2 = $login_goldCoin2+300;
$pay_goldCoin3 = $login_goldCoin3+300;
$pay_goldCoin4 = $login_goldCoin4+300;
$pay_sliverCoin1 = $login_sliverCoin1+300;
$pay_sliverCoin2 = $login_sliverCoin2+300;
$pay_sliverCoin3 = $login_sliverCoin3+300;
$pay_sliverCoin4 = $login_sliverCoin4+300;

$levelupgrade_roleLevel1 = $pay_roleLevel1+1;
$levelupgrade_roleLevel2 = $pay_roleLevel2+1;
$levelupgrade_roleLevel3 = $pay_roleLevel3+1;
$levelupgrade_roleLevel4 = $pay_roleLevel4+1;
$levelupgrade_roleVip1 = $pay_roleVip1+1;
$levelupgrade_roleVip2 = $pay_roleVip2+1;
$levelupgrade_roleVip3 = $pay_roleVip3+1;
$levelupgrade_roleVip4 = $pay_roleVip4+1;
$levelupgrade_goldCoin1 = $pay_goldCoin1+300;
$levelupgrade_goldCoin2 = $pay_goldCoin2+300;
$levelupgrade_goldCoin3 = $pay_goldCoin3+300;
$levelupgrade_goldCoin4 = $pay_goldCoin4+300;
$levelupgrade_sliverCoin1 = $pay_sliverCoin1+300;
$levelupgrade_sliverCoin2 = $pay_sliverCoin2+300;
$levelupgrade_sliverCoin3 = $pay_sliverCoin3+300;
$levelupgrade_sliverCoin4 = $pay_sliverCoin4+300;

$viplevelup_roleLevel1 = $pay_roleLevel1+1;
$viplevelup_roleLevel2 = $pay_roleLevel2+1;
$viplevelup_roleLevel3 = $pay_roleLevel3+1;
$viplevelup_roleLevel4 = $pay_roleLevel4+1;
$viplevelup_roleVip1 = $pay_roleVip1+1;
$viplevelup_roleVip2 = $pay_roleVip2+1;
$viplevelup_roleVip3 = $pay_roleVip3+1;
$viplevelup_roleVip4 = $pay_roleVip4+1;
$viplevelup_goldCoin1 = $pay_goldCoin1+300;
$viplevelup_goldCoin2 = $pay_goldCoin2+300;
$viplevelup_goldCoin3 = $pay_goldCoin3+300;
$viplevelup_goldCoin4 = $pay_goldCoin4+300;
$viplevelup_sliverCoin1 = $pay_sliverCoin1+300;
$viplevelup_sliverCoin2 = $pay_sliverCoin2+300;
$viplevelup_sliverCoin3 = $pay_sliverCoin3+300;
$viplevelup_sliverCoin4 = $pay_sliverCoin4+300;

$url_razor_clientdata = "http://127.0.0.1:8888/razor_clientdata";
$url_razor_install = "http://127.0.0.1:8888/razor_install";
$url_razor_register = "http://127.0.0.1:8888/razor_register";
$url_razor_createrole = "http://127.0.0.1:8888/razor_createrole";
$url_razor_login = "http://127.0.0.1:8888/razor_login";
$url_razor_pay = "http://127.0.0.1:8888/razor_pay";
$url_razor_realtimeonlineusers = "http://127.0.0.1:8888/razor_realtimeonlineusers";
$url_razor_levelupgrade = "http://127.0.0.1:8888/razor_levelupgrade";
$url_razor_viplevelup = "http://127.0.0.1:8888/razor_viplevelup";

$data_razor_clientdata_1 = json_encode(array (
    'serviceversion' => '',
    'name' => '',
    'version' => '1.0',
    'appId' => '1',
    'platform' => '1',
    'osversion' => '',
    'osaddtional' => '',
    'language' => '',
    'resolution' => '',
    'ismobiledevice' => '',
    'devicename' => '',
    'deviceid' => $deviceid1,
    'defaultbrowser' => '',
    'javasupport' => '',
    'flashversion' => '',
    'modulename' => '',
    'imei' => '',
    'imsi' => '',
    'salt' => '',
    'havegps' => '',
    'havebt' => '',
    'havewifi' => '',
    'havegravity' => '',
    'wifimac' => '',
    'latitude' => '',
    'longitude' => '',
    'date' => $currenttime,
    'clientip' => '',
    'productkey' => 'f0e1815b61767ffa9206d4dc1048b26e',
    'service_supplier' => '',
    'country' => '',
    'region' => '',
    'city' => '',
    'street' => '',
    'streetno' => '',
    'postcode' => '',
    'network' => '',
    'isjailbroken' => '',
    'useridentifier' => '',
));
$data_razor_clientdata_2 = json_encode(array (
  'serviceversion' => '',
  'name' => '',
  'version' => '2.0',
  'appId' => '1',
  'platform' => '1',
  'osversion' => '',
  'osaddtional' => '',
  'language' => '',
  'resolution' => '',
  'ismobiledevice' => '',
  'devicename' => '',
  'deviceid' => $deviceid2,
  'defaultbrowser' => '',
  'javasupport' => '',
  'flashversion' => '',
  'modulename' => '',
  'imei' => '',
  'imsi' => '',
  'salt' => '',
  'havegps' => '',
  'havebt' => '',
  'havewifi' => '',
  'havegravity' => '',
  'wifimac' => '',
  'latitude' => '',
  'longitude' => '',
  'date' => $currenttime,
  'clientip' => '',
  'productkey' => 'cc58b7e837bfa1cd2aa060d144f8335d',
  'service_supplier' => '',
  'country' => '',
  'region' => '',
  'city' => '',
  'street' => '',
  'streetno' => '',
  'postcode' => '',
  'network' => '',
  'isjailbroken' => '',
  'useridentifier' => '',
));
$data_razor_clientdata_3 = json_encode(array (
  'serviceversion' => '',
  'name' => '',
  'version' => '1.0',
  'appId' => '9',
  'platform' => '2',
  'osversion' => '',
  'osaddtional' => '',
  'language' => '',
  'resolution' => '',
  'ismobiledevice' => '',
  'devicename' => '',
  'deviceid' => $deviceid3,
  'defaultbrowser' => '',
  'javasupport' => '',
  'flashversion' => '',
  'modulename' => '',
  'imei' => '',
  'imsi' => '',
  'salt' => '',
  'havegps' => '',
  'havebt' => '',
  'havewifi' => '',
  'havegravity' => '',
  'wifimac' => '',
  'latitude' => '',
  'longitude' => '',
  'date' => $currenttime,
  'clientip' => '',
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'service_supplier' => '',
  'country' => '',
  'region' => '',
  'city' => '',
  'street' => '',
  'streetno' => '',
  'postcode' => '',
  'network' => '',
  'isjailbroken' => '',
  'useridentifier' => '',
));
$data_razor_clientdata_4 = json_encode(array (
  'serviceversion' => '',
  'name' => '',
  'version' => '2.0',
  'appId' => '9',
  'platform' => '2',
  'osversion' => '',
  'osaddtional' => '',
  'language' => '',
  'resolution' => '',
  'ismobiledevice' => '',
  'devicename' => '',
  'deviceid' => $deviceid4,
  'defaultbrowser' => '',
  'javasupport' => '',
  'flashversion' => '',
  'modulename' => '',
  'imei' => '',
  'imsi' => '',
  'salt' => '',
  'havegps' => '',
  'havebt' => '',
  'havewifi' => '',
  'havegravity' => '',
  'wifimac' => '',
  'latitude' => '',
  'longitude' => '',
  'date' => $currenttime,
  'clientip' => '',
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'service_supplier' => '',
  'country' => '',
  'region' => '',
  'city' => '',
  'street' => '',
  'streetno' => '',
  'postcode' => '',
  'network' => '',
  'isjailbroken' => '',
  'useridentifier' => '',
));
list($return_code, $return_content) = http_post_data($url_razor_clientdata, $data_razor_clientdata_1);
list($return_code, $return_content) = http_post_data($url_razor_clientdata, $data_razor_clientdata_2);
list($return_code, $return_content) = http_post_data($url_razor_clientdata, $data_razor_clientdata_3);
list($return_code, $return_content) = http_post_data($url_razor_clientdata, $data_razor_clientdata_4);

$data_razor_install_1 = json_encode(array (
  'install_date' => $currentday,
  'chId' => '1',
  'appId' => '1',
  'version' => '1.0',
  'productkey' => 'f0e1815b61767ffa9206d4dc1048b26e',
  'deviceid' => $deviceid1,
  'install_time' => $currenttime,
));
$data_razor_install_2 = json_encode(array (
  'install_date' => $currentday,
  'chId' => '2',
  'appId' => '1',
  'version' => '2.0',
  'productkey' => 'cc58b7e837bfa1cd2aa060d144f8335d',
  'deviceid' => $deviceid2,
  'install_time' => $currenttime,
));
$data_razor_install_3 = json_encode(array (
  'install_date' => $currentday,
  'chId' => '5',
  'appId' => '9',
  'version' => '1.0',
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'deviceid' => $deviceid3,
  'install_time' => $currenttime,
));
$data_razor_install_4 = json_encode(array (
  'install_date' => $currentday,
  'chId' => '5',
  'appId' => '9',
  'version' => '2.0',
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'deviceid' => $deviceid4,
  'install_time' => $currenttime,
));
list($return_code, $return_content) = http_post_data($url_razor_install, $data_razor_install_1);
list($return_code, $return_content) = http_post_data($url_razor_install, $data_razor_install_2);
list($return_code, $return_content) = http_post_data($url_razor_install, $data_razor_install_3);
list($return_code, $return_content) = http_post_data($url_razor_install, $data_razor_install_4);

$data_razor_register_1 = json_encode(array (
  'register_date' => $currentday,
  'chId' => '1',
  'appId' => '1',
  'version' => '1.0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid1,
  'productkey' => 'f0e1815b61767ffa9206d4dc1048b26e',
  'deviceid' => $deviceid1,
  'register_time' => $currenttime,
));
$data_razor_register_2 = json_encode(array (
  'register_date' => $currentday,
  'chId' => '2',
  'appId' => '1',
  'version' => '2.0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid2,
  'productkey' => 'cc58b7e837bfa1cd2aa060d144f8335d',
  'deviceid' => $deviceid2,
  'register_time' => $currenttime,
));
$data_razor_register_3 = json_encode(array (
  'register_date' => $currentday,
  'chId' => '5',
  'appId' => '9',
  'version' => '1.0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid3,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'deviceid' => $deviceid3,
  'register_time' => $currenttime,
));
$data_razor_register_4 = json_encode(array (
  'register_date' => $currentday,
  'chId' => '5',
  'appId' => '9',
  'version' => '2.0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid4,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'deviceid' => $deviceid4,
  'register_time' => $currenttime,
));
list($return_code, $return_content) = http_post_data($url_razor_register, $data_razor_register_1);
list($return_code, $return_content) = http_post_data($url_razor_register, $data_razor_register_2);
list($return_code, $return_content) = http_post_data($url_razor_register, $data_razor_register_3);
list($return_code, $return_content) = http_post_data($url_razor_register, $data_razor_register_4);

$data_razor_createrole_1 = json_encode(array (
  'create_role_date' => $currentday,
  'chId' => '1',
  'subSrvId' => '',
  'srvId' => '1',
  'appId' => '1',
  'version' => '1.0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'obligate5' => '',
  'obligate6' => '',
  'userId' => $userid1,
  'productkey' => 'f0e1815b61767ffa9206d4dc1048b26e',
  'deviceid' => $deviceid1,
  'create_role_time' => $currenttime,
  'roleId' => $roleid1,
  'roleName' => $rolename1,
  'roleLevel' => '1',
  'roleSex' => '0',
  'roleVip' => '0',
  'goldCoin' => '0',
  'sliverCoin' => '0',
));
$data_razor_createrole_2 = json_encode(array (
  'create_role_date' => $currentday,
  'chId' => '2',
  'subSrvId' => '',
  'srvId' => '2',
  'appId' => '1',
  'version' => '2.0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'obligate5' => '',
  'obligate6' => '',
  'userId' => $userid2,
  'productkey' => 'cc58b7e837bfa1cd2aa060d144f8335d',
  'deviceid' => $deviceid2,
  'create_role_time' => $currenttime,
  'roleId' => $roleid2,
  'roleName' => $rolename2,
  'roleLevel' => '1',
  'roleSex' => '1',
  'roleVip' => '0',
  'goldCoin' => '0',
  'sliverCoin' => '0',
));
$data_razor_createrole_3 = json_encode(array (
  'create_role_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '9',
  'appId' => '9',
  'version' => '1.0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'obligate5' => '',
  'obligate6' => '',
  'userId' => $userid3,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'deviceid' => $deviceid3,
  'create_role_time' => $currenttime,
  'roleId' => $roleid3,
  'roleName' => $rolename3,
  'roleLevel' => '1',
  'roleSex' => '0',
  'roleVip' => '0',
  'goldCoin' => '0',
  'sliverCoin' => '0',
));
$data_razor_createrole_4 = json_encode(array (
  'create_role_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '14',
  'appId' => '9',
  'version' => '2.0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'obligate5' => '',
  'obligate6' => '',
  'userId' => $userid4,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'deviceid' => $deviceid4,
  'create_role_time' => $currenttime,
  'roleId' => $roleid4,
  'roleName' => $rolename4,
  'roleLevel' => '1',
  'roleSex' => '1',
  'roleVip' => '0',
  'goldCoin' => '0',
  'sliverCoin' => '0',
));
list($return_code, $return_content) = http_post_data($url_razor_createrole, $data_razor_createrole_1);
list($return_code, $return_content) = http_post_data($url_razor_createrole, $data_razor_createrole_2);
list($return_code, $return_content) = http_post_data($url_razor_createrole, $data_razor_createrole_3);
list($return_code, $return_content) = http_post_data($url_razor_createrole, $data_razor_createrole_4);

$data_razor_login_1 = json_encode(array (
  'login_date' => $currentday,
  'chId' => '1',
  'subSrvId' => '',
  'srvId' => '1',
  'appId' => '1',
  'version' => '1.0',
  'type' => 'login',
  'offlineSettleTime' => '0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid1,
  'roleId' => $roleid1,
  'roleLevel' => $login_roleLevel1,
  'roleVip' => $login_roleVip1,
  'goldCoin' => $login_goldCoin1,
  'sliverCoin' => $login_goldCoin1,
  'productkey' => 'f0e1815b61767ffa9206d4dc1048b26e',
  'login_time' => $currenttime,
  'deviceid' => $deviceid1,
  'ip' => '8.8.8.8',
));
$data_razor_login_11 = json_encode(array (
  'login_date' => $currentday,
  'chId' => '1',
  'subSrvId' => '',
  'srvId' => '1',
  'appId' => '1',
  'version' => '1.0',
  'type' => 'logout',
  'offlineSettleTime' => rand(10,10000),
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid1,
  'roleId' => $roleid1,
  'roleLevel' => $login_roleLevel11,
  'roleVip' => $login_roleVip11,
  'goldCoin' => $login_goldCoin11,
  'sliverCoin' => $login_goldCoin11,
  'productkey' => 'f0e1815b61767ffa9206d4dc1048b26e',
  'login_time' => $currenttime,
  'deviceid' => $deviceid1,
  'ip' => '8.8.8.8',
));
$data_razor_login_2 = json_encode(array (
  'login_date' => $currentday,
  'chId' => '2',
  'subSrvId' => '',
  'srvId' => '2',
  'appId' => '1',
  'version' => '2.0',
  'type' => 'login',
  'offlineSettleTime' => '0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid2,
  'roleId' => $roleid2,
  'roleLevel' => $login_roleLevel2,
  'roleVip' => $login_roleVip2,
  'goldCoin' => $login_goldCoin2,
  'sliverCoin' => $login_goldCoin2,
  'productkey' => 'cc58b7e837bfa1cd2aa060d144f8335d',
  'login_time' => $currenttime,
  'deviceid' => $deviceid2,
  'ip' => '114.114.114.114',
));
$data_razor_login_21 = json_encode(array (
  'login_date' => $currentday,
  'chId' => '2',
  'subSrvId' => '',
  'srvId' => '2',
  'appId' => '1',
  'version' => '2.0',
  'type' => 'logout',
  'offlineSettleTime' => rand(10,10000),
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid2,
  'roleId' => $roleid2,
  'roleLevel' => $login_roleLevel21,
  'roleVip' => $login_roleVip21,
  'goldCoin' => $login_goldCoin21,
  'sliverCoin' => $login_goldCoin21,
  'productkey' => 'cc58b7e837bfa1cd2aa060d144f8335d',
  'login_time' => $currenttime,
  'deviceid' => $deviceid2,
  'ip' => '114.114.114.114',
));
$data_razor_login_3 = json_encode(array (
  'login_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '9',
  'appId' => '9',
  'version' => '1.0',
  'type' => 'login',
  'offlineSettleTime' => '0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid3,
  'roleId' => $roleid3,
  'roleLevel' => $login_roleLevel3,
  'roleVip' => $login_roleVip3,
  'goldCoin' => $login_goldCoin3,
  'sliverCoin' => $login_goldCoin3,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'login_time' => $currenttime,
  'deviceid' => $deviceid3,
  'ip' => '192.168.1.1',
));
$data_razor_login_31 = json_encode(array (
  'login_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '9',
  'appId' => '9',
  'version' => '1.0',
  'type' => 'logout',
  'offlineSettleTime' => rand(10,10000),
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid3,
  'roleId' => $roleid3,
  'roleLevel' => $login_roleLevel31,
  'roleVip' => $login_roleVip31,
  'goldCoin' => $login_goldCoin31,
  'sliverCoin' => $login_goldCoin31,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'login_time' => $currenttime,
  'deviceid' => $deviceid3,
  'ip' => '192.168.1.1',
));
$data_razor_login_4 = json_encode(array (
  'login_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '9',
  'appId' => '9',
  'version' => '1.0',
  'type' => 'login',
  'offlineSettleTime' => '0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid4,
  'roleId' => $roleid4,
  'roleLevel' => $login_roleLevel4,
  'roleVip' => $login_roleVip4,
  'goldCoin' => $login_goldCoin4,
  'sliverCoin' => $login_goldCoin4,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'login_time' => $currenttime,
  'deviceid' => $deviceid4,
  'ip' => '192.168.1.254',
));
$data_razor_login_41 = json_encode(array (
  'login_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '9',
  'appId' => '9',
  'version' => '1.0',
  'type' => 'logout',
  'offlineSettleTime' => rand(10,10000),
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid4,
  'roleId' => $roleid4,
  'roleLevel' => $login_roleLevel41,
  'roleVip' => $login_roleVip41,
  'goldCoin' => $login_goldCoin41,
  'sliverCoin' => $login_goldCoin41,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'login_time' => $currenttime,
  'deviceid' => $deviceid4,
  'ip' => '192.168.1.254',
));
list($return_code, $return_content) = http_post_data($url_razor_login, $data_razor_login_1);
list($return_code, $return_content) = http_post_data($url_razor_login, $data_razor_login_11);
list($return_code, $return_content) = http_post_data($url_razor_login, $data_razor_login_2);
list($return_code, $return_content) = http_post_data($url_razor_login, $data_razor_login_21);
list($return_code, $return_content) = http_post_data($url_razor_login, $data_razor_login_3);
list($return_code, $return_content) = http_post_data($url_razor_login, $data_razor_login_31);
list($return_code, $return_content) = http_post_data($url_razor_login, $data_razor_login_4);
list($return_code, $return_content) = http_post_data($url_razor_login, $data_razor_login_41);

$data_razor_pay_1 = json_encode(array (
  'pay_date' => $currentday,
  'chId' => '1',
  'subSrvId' => '',
  'srvId' => '1',
  'appId' => '1',
  'version' => '1.0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid1,
  'productkey' => 'f0e1815b61767ffa9206d4dc1048b26e',
  'deviceid' => $deviceid1,
  'pay_time' => $currenttime,
  'roleId' => $roleid1,
  'roleName' => $rolename1,
  'roleLevel' => $pay_roleLevel1,
  'roleVip' => $pay_roleVip1,
  'goldCoin' => $pay_goldCoin1,
  'sliverCoin' => $pay_sliverCoin1,
  'pay_unit' => 'rmb',
  'pay_type' => 'recharge',
  'pay_amount' => rand(10,1000),
  'coinAmount' => $pay_goldCoin1,
  'orderId' => $orderid1,
));
$data_razor_pay_2 = json_encode(array (
  'pay_date' => $currentday,
  'chId' => '2',
  'subSrvId' => '',
  'srvId' => '2',
  'appId' => '1',
  'version' => '2.0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid2,
  'productkey' => 'cc58b7e837bfa1cd2aa060d144f8335d',
  'deviceid' => $deviceid2,
  'pay_time' => $currenttime,
  'roleId' => $roleid2,
  'roleName' => $rolename2,
  'roleLevel' => $pay_roleLevel2,
  'roleVip' => $pay_roleVip2,
  'goldCoin' => $pay_goldCoin2,
  'sliverCoin' => $pay_sliverCoin2,
  'pay_unit' => 'rmb',
  'pay_type' => 'recharge',
  'pay_amount' => rand(10,1000),
  'coinAmount' => $pay_goldCoin2,
  'orderId' => $orderid2,
));
$data_razor_pay_3 = json_encode(array (
  'pay_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '9',
  'appId' => '9',
  'version' => '1.0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid3,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'deviceid' => $deviceid3,
  'pay_time' => $currenttime,
  'roleId' => $roleid3,
  'roleName' => $rolename3,
  'roleLevel' => $pay_roleLevel3,
  'roleVip' => $pay_roleVip3,
  'goldCoin' => $pay_goldCoin3,
  'sliverCoin' => $pay_sliverCoin3,
  'pay_unit' => 'rmb',
  'pay_type' => 'recharge',
  'pay_amount' => rand(10,1000),
  'coinAmount' => $pay_goldCoin3,
  'orderId' => $orderid3,
));
$data_razor_pay_4 = json_encode(array (
  'pay_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '14',
  'appId' => '9',
  'version' => '2.0',
  'obligate1' => '',
  'obligate2' => '',
  'obligate3' => '',
  'obligate4' => '',
  'userId' => $userid4,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'deviceid' => $deviceid4,
  'pay_time' => $currenttime,
  'roleId' => $roleid4,
  'roleName' => $rolename4,
  'roleLevel' => $pay_roleLevel4,
  'roleVip' => $pay_roleVip4,
  'goldCoin' => $pay_goldCoin4,
  'sliverCoin' => $pay_sliverCoin4,
  'pay_unit' => 'rmb',
  'pay_type' => 'recharge',
  'pay_amount' => rand(10,1000),
  'coinAmount' => $pay_goldCoin4,
  'orderId' => $orderid4,
));
list($return_code, $return_content) = http_post_data($url_razor_pay, $data_razor_pay_1);
list($return_code, $return_content) = http_post_data($url_razor_pay, $data_razor_pay_2);
list($return_code, $return_content) = http_post_data($url_razor_pay, $data_razor_pay_3);
list($return_code, $return_content) = http_post_data($url_razor_pay, $data_razor_pay_4);

$data_razor_realtimeonlineusers_1 = json_encode(array (
  'count_date' => $currentday,
  'chId' => '1',
  'subSrvId' => '',
  'srvId' => '1',
  'appId' => '1',
  'version' => '1.0',
  'count_time' => $currenttime,
  'onlineusers' => rand(10,1000),
  'productkey' => 'f0e1815b61767ffa9206d4dc1048b26e',
));
$data_razor_realtimeonlineusers_2 = json_encode(array (
  'count_date' => $currentday,
  'chId' => '2',
  'subSrvId' => '',
  'srvId' => '2',
  'appId' => '1',
  'version' => '2.0',
  'count_time' => $currenttime,
  'onlineusers' => rand(10,1000),
  'productkey' => 'cc58b7e837bfa1cd2aa060d144f8335d',
));
$data_razor_realtimeonlineusers_3 = json_encode(array (
  'count_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '9',
  'appId' => '9',
  'version' => '1.0',
  'count_time' => $currenttime,
  'onlineusers' => rand(10,1000),
  'productkey' => '3fa07576422a632531e161892cc959b6',
));
$data_razor_realtimeonlineusers_4 = json_encode(array (
  'count_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '14',
  'appId' => '9',
  'version' => '2.0',
  'count_time' => $currenttime,
  'onlineusers' => rand(10,1000),
  'productkey' => '3fa07576422a632531e161892cc959b6',
));
list($return_code, $return_content) = http_post_data($url_razor_realtimeonlineusers, $data_razor_realtimeonlineusers_1);
list($return_code, $return_content) = http_post_data($url_razor_realtimeonlineusers, $data_razor_realtimeonlineusers_2);
list($return_code, $return_content) = http_post_data($url_razor_realtimeonlineusers, $data_razor_realtimeonlineusers_3);
list($return_code, $return_content) = http_post_data($url_razor_realtimeonlineusers, $data_razor_realtimeonlineusers_4);


$data_razor_levelupgrade_1 = json_encode(array (
  'levelupgrade_date' => $currentday,
  'chId' => '1',
  'subSrvId' => '',
  'srvId' => '1',
  'appId' => '1',
  'version' => '1.0',
  'userId' => $userid1,
  'productkey' => 'f0e1815b61767ffa9206d4dc1048b26e',
  'deviceid' => $deviceid1,
  'levelupgrade_time' => $currenttime,
  'roleId' => $roleid1,
  'roleName' => $rolename1,
  'roleLevel' => $levelupgrade_roleLevel1,
  'roleVip' => $levelupgrade_roleVip1,
  'goldCoin' => $levelupgrade_goldCoin1,
  'sliverCoin' => $levelupgrade_sliverCoin1,
));
$data_razor_levelupgrade_2 = json_encode(array (
  'levelupgrade_date' => $currentday,
  'chId' => '2',
  'subSrvId' => '',
  'srvId' => '2',
  'appId' => '1',
  'version' => '2.0',
  'userId' => $userid2,
  'productkey' => 'cc58b7e837bfa1cd2aa060d144f8335d',
  'deviceid' => $deviceid2,
  'levelupgrade_time' => $currenttime,
  'roleId' => $roleid2,
  'roleName' => $rolename2,
  'roleLevel' => $levelupgrade_roleLevel2,
  'roleVip' => $levelupgrade_roleVip2,
  'goldCoin' => $levelupgrade_goldCoin2,
  'sliverCoin' => $levelupgrade_sliverCoin2,
));
$data_razor_levelupgrade_3 = json_encode(array (
  'levelupgrade_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '9',
  'appId' => '9',
  'version' => '1.0',
  'userId' => $userid3,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'deviceid' => $deviceid3,
  'levelupgrade_time' => $currenttime,
  'roleId' => $roleid3,
  'roleName' => $rolename3,
  'roleLevel' => $levelupgrade_roleLevel3,
  'roleVip' => $levelupgrade_roleVip3,
  'goldCoin' => $levelupgrade_goldCoin3,
  'sliverCoin' => $levelupgrade_sliverCoin3,
));
$data_razor_levelupgrade_4 = json_encode(array (
  'levelupgrade_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '14',
  'appId' => '9',
  'version' => '2.0',
  'userId' => $userid4,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'deviceid' => $deviceid4,
  'levelupgrade_time' => $currenttime,
  'roleId' => $roleid4,
  'roleName' => $rolename4,
  'roleLevel' => $levelupgrade_roleLevel4,
  'roleVip' => $levelupgrade_roleVip4,
  'goldCoin' => $levelupgrade_goldCoin4,
  'sliverCoin' => $levelupgrade_sliverCoin4,
));
list($return_code, $return_content) = http_post_data($url_razor_levelupgrade, $data_razor_levelupgrade_1);
list($return_code, $return_content) = http_post_data($url_razor_levelupgrade, $data_razor_levelupgrade_2);
list($return_code, $return_content) = http_post_data($url_razor_levelupgrade, $data_razor_levelupgrade_3);
list($return_code, $return_content) = http_post_data($url_razor_levelupgrade, $data_razor_levelupgrade_4);

$data_razor_viplevelup_1 = json_encode(array (
  'viplevelup_date' => $currentday,
  'chId' => '1',
  'subSrvId' => '',
  'srvId' => '1',
  'appId' => '1',
  'version' => '1.0',
  'userId' => $userid1,
  'productkey' => 'f0e1815b61767ffa9206d4dc1048b26e',
  'deviceid' => $deviceid1,
  'viplevelup_time' => $currenttime,
  'roleId' => $roleid1,
  'roleName' => $rolename1,
  'roleLevel' => $viplevelup_roleLevel1,
  'currentRoleVip' => $viplevelup_roleVip1,
  'beforeRoleVip' => $pay_roleVip1,
  'goldCoin' => $viplevelup_goldCoin1,
  'sliverCoin' => $viplevelup_sliverCoin1,
));
$data_razor_viplevelup_2 = json_encode(array (
  'viplevelup_date' => $currentday,
  'chId' => '2',
  'subSrvId' => '',
  'srvId' => '2',
  'appId' => '1',
  'version' => '2.0',
  'userId' => $userid2,
  'productkey' => 'cc58b7e837bfa1cd2aa060d144f8335d',
  'deviceid' => $deviceid2,
  'viplevelup_time' => $currenttime,
  'roleId' => $roleid2,
  'roleName' => $rolename2,
  'roleLevel' => $viplevelup_roleLevel2,
  'currentRoleVip' => $viplevelup_roleVip2,
  'beforeRoleVip' => $pay_roleVip2,
  'goldCoin' => $viplevelup_goldCoin2,
  'sliverCoin' => $viplevelup_sliverCoin2,
));
$data_razor_viplevelup_3 = json_encode(array (
  'viplevelup_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '9',
  'appId' => '9',
  'version' => '1.0',
  'userId' => $userid3,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'deviceid' => $deviceid3,
  'viplevelup_time' => $currenttime,
  'roleId' => $roleid3,
  'roleName' => $rolename3,
  'roleLevel' => $viplevelup_roleLevel3,
  'currentRoleVip' => $viplevelup_roleVip3,
  'beforeRoleVip' => $pay_roleVip3,
  'goldCoin' => $viplevelup_goldCoin3,
  'sliverCoin' => $viplevelup_sliverCoin3,
));
$data_razor_viplevelup_4 = json_encode(array (
  'viplevelup_date' => $currentday,
  'chId' => '5',
  'subSrvId' => '',
  'srvId' => '14',
  'appId' => '9',
  'version' => '2.0',
  'userId' => $userid4,
  'productkey' => '3fa07576422a632531e161892cc959b6',
  'deviceid' => $deviceid4,
  'viplevelup_time' => $currenttime,
  'roleId' => $roleid4,
  'roleName' => $rolename4,
  'roleLevel' => $viplevelup_roleLevel4,
  'currentRoleVip' => $viplevelup_roleVip4,
  'beforeRoleVip' => $pay_roleVip4,
  'goldCoin' => $viplevelup_goldCoin4,
  'sliverCoin' => $viplevelup_sliverCoin4,
));
list($return_code, $return_content) = http_post_data($url_razor_viplevelup, $data_razor_viplevelup_1);
list($return_code, $return_content) = http_post_data($url_razor_viplevelup, $data_razor_viplevelup_2);
list($return_code, $return_content) = http_post_data($url_razor_viplevelup, $data_razor_viplevelup_3);
list($return_code, $return_content) = http_post_data($url_razor_viplevelup, $data_razor_viplevelup_4);
?>
